# 210 Review
We'll introduce ourselves to Jupyter Notebooks today while reviewing the main concepts from our class :) 

Jupyter Notebooks can have text cells and code cells mixed together!

## Data Types
Python has several built-in data types. Knowing how they work is essential for writing correct code.
- **int**: whole numbers (e.g., `5`, `-2`)
- **float**: decimal numbers (e.g., `3.14`, `-0.5`)
- **str**: text (e.g., `'hello'`)
- **bool**: `True` or `False`
- **list**: ordered, mutable collection (e.g., `[1, 2, 3]`)
- **tuple**: ordered, immutable collection (e.g., `(1, 2, 3)`)
- **dict**: key-value pairs (e.g., `{'a': 1, 'b': 2}`)

## Extra Info
- Use `type(x)` to check a variable's type.
- Lists are mutable: changing one element changes the list.
- Assigning one list to another (e.g., `B = A`) means both refer to the same object!
- Use `B = A.copy()` to make a copy of a list.

In [5]:
# Try creating variables of different types below, and check their types with type().
# For example: a = 5; print(type(a))

a = 1
b = "hello"
c = True
d = 3.14
e = [1, 2, 3]
f = (1, 2, 3)
g = {1: "one", 2: "two"}

print(type(e))

#if we add a float to a bool, does it's type change? Code to verify. 
h = d + c
print(h)

#Can a dictionary contain another dictionary as a value? Code to verify. e
d = { 1: { "one":1}, 2: {"two":2}}
print(d)



<class 'list'>
4.140000000000001
{1: {'one': 1}, 2: {'two': 2}}


## Control Flow: for, if, while
Control flow lets you decide what your code does and how often it runs.
- **for loops**: repeat for each item in a sequence (list, string, etc.)
    ```python
    for i in range(3):
        print(i)  # prints 0, 1, 2
    ```
- **if statements**: run code only if a condition is true
    ```python
    if x > 0:
        print('Positive!')
    ```
- **while loops**: repeat as long as a condition is true
    ```python
    count = 0
    while count < 3:
        print(count)
        count += 1
    ```
- Indentation matters!

Use a `for` loop when iterating through a sequence or a known range. Use a `while` loop when repetition should continue until a condition changes.

In [15]:
# Write a for loop that prints the even numbers up to 20

for i in range(0,21,2):
    print(i)



# Write a while loop that counts down from 10 to 0.
i = 10
while i>=0:
    print(i)
    i-=1



0
2
4
6
8
10
12
14
16
18
20
10
9
8
7
6
5
4
3
2
1
0


### The `break` and `continue` Statements in Loops
- `break` immediately exits the loop, skipping all remaining iterations.
- `continue` skips the rest of the code in the current iteration and moves to the next one.
Use these to control the flow of your loops!

In [17]:
# Example: Print only odd numbers from 1 to 10 using continue
for i in range(11):
    if i%2==0:
        continue
    print(i)

1
3
5
7
9


In [26]:
# increment and print a counter repeatedly
# starting from 0, with a 20% random chance
# of stopping the counter and ending the code.

import random as random

counter = 0

while True:
    print(counter)
    if random.random() < 0.2:
        break
    counter += 1

0
1
2
3
4


## Numpy Arrays: Initializing, Indexing, Slicing
Numpy arrays are powerful for numerical data. They are like lists, but faster and support math operations directly.
- **Import numpy**: `import numpy as np`
- **Create arrays**:
    - `np.array([1, 2, 3])`
    - `np.zeros(4)` (array of zeros)
    - `np.ones((2, 3))` (2x3 array of ones)
    - `np.arange(5)` (array: 0,1,2,3,4)
- **Indexing**: starts at 0. `A[1]` is the second element.
- **Slicing**: `A[1:4]` gives elements 1,2,3 (not 4).
- **Arrays are mutable**: changing one element changes the array.
- **Broadcasting**: you can add, subtract, multiply arrays and numbers directly.
**Tips:**
- Use `.shape` to check array dimensions.
- Use `.copy()` to avoid reference issues.

In [49]:
# Import NumPy and create a 1D array with the integers from 1 through 20.
import numpy as np

arr = np.arange(1,21,dtype= np.int32)
print(arr)

# Print the first five elements and the final three elements of the array.
print(arr[:5])
print(arr[-3:])

# Use a Boolean condition to print the values that are both even and greater than 10.
bool_mask = (arr[:] > 10) & (arr[:]%2==0)
print(bool_mask)
print(arr[bool_mask])

# Change the first element to 100, reshape the array into a 4-by-5 array, and print the result.
arr[0] = 100
print(arr)
arr = arr.reshape(4,5)
print(arr.shape)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[1 2 3 4 5]
[18 19 20]
[False False False False False False False False False False False  True
 False  True False  True False  True False  True]
[12 14 16 18 20]
[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]
(4, 5)


## Pandas DataFrames: WineQT Example
- **Import pandas**: `import pandas as pd`
- **Load data**: `df = pd.read_csv('WineQT.csv')`
- **View data**: `df.head()` shows the first few rows.
- **Access columns**: `df['quality']`, `df[['alcohol','quality']]`
- **Select specific rows**: `df[df['quality'] > 5]`
- **Summary stats**: `df['alcohol'].mean()`, `df.describe()`
- **Column names are case-sensitive!**
**Tips:**
- Use `df['quality'].value_counts()` to see how many times each quality score appears.
- Use `df['quality'].unique()` to see the unique values in the quality column. 

In [53]:
pip install pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 4.1 MB/s  0:00:02eta 0:00:010m
Note: you may need to restart the kernel to use updated packages.


In [ ]:
import pandas as pd
df = pd.read_csv(r"C:\Users\shivam\Downloads\WineQT.csv")



# Print the first 5 rows
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\shivam\\Downloads\\WineQT.csv'

In [ ]:
#what values appear in the quality column, and what is its data type? 


#what is the average quality? 


#How many wines have quality 5? 


#what is the average quality of wined with alcohol above the mean alcohol value, versus below it? 


## Functions
Write a function called `strongest_wine(data, minimum_quality)` that takes a DataFrame and a minimum quality score. It should return the row for the wine with the highest `alcohol` value among wines whose `quality` is at least the requested score.

Call your function with minimum quality scores of `6` and `7`. Compare the returned wines.

In [ ]:
# Define strongest_wine(data, minimum_quality) here.
# Filter to wines with quality at least minimum_quality, then return the row with the highest alcohol value.


# Call your function with minimum_quality values of 6 and 7.


## Reference Behavior & Mutability
In Python, some objects are **mutable** (can change), and some are **immutable** (cannot change). Lists, numpy arrays, and pandas DataFrames are mutable.
- **Assignment does NOT copy!** `B = A` means B and A point to the same object.
- To make a true copy:
    - For lists, arrays, or df's: `B = A.copy()`
- Changing one will change the other if you didn't copy!
Example:
```python
A = [1, 2, 3]
B = A
B[0] = 99
print(A)  # [99, 2, 3]
```
**Tips:**
- Use `id(x)` to check if two variables point to the same object.
- Use `.copy()` to avoid accidental changes.

In [ ]:
# Do we have the same behavior with dataframes? Write code to test this. 
